#!/usr/bin/env php
<?php

if (file_exists(__DIR__ . '/../../autoload.php')) {
    require __DIR__ . '/../../autoload.php';
} else {
    require __DIR__ . '/vendor/autoload.php';
}

$dbdiff = new DBDiff\DBDiff;
$res = $dbdiff->setSourceDB(['user'=>'root','password'=>'123456','port'=>3306,'host'=>'127.0.0.1','db_name'=>'db1'])
->setTargetDB(['user'=>'root','password'=>'123456','port'=>3306,'host'=>'127.0.0.1','db_name' => 'db2'])
->run();
var_dump($res);
