#!/usr/bin/env php
<?php

if (file_exists(__DIR__ . '/../../autoload.php')) {
    require __DIR__ . '/../../autoload.php';
} else {
    require __DIR__ . '/vendor/autoload.php';
}

$dbdiff = new DBDiff\DBDiff;
$res = $dbdiff->setSourceTable('hyatt')->setTargetTable('hyatt1')->run();
var_dump($res);
