<?php namespace DBDiff;

use Illuminate\View\Compilers\BladeCompiler;
use Illuminate\Filesystem\Filesystem;


class Templater {

    function __construct($params, $up, $down) {
        $this->params = $params;
        $this->up = $up;
        $this->down = $down;
    }
    
    public function output() {
        $content = $this->getComments();
        $content .= $this->getContent();
        return $content;
    }

    private function getComments() {
        if (!$this->params->nocomments) {
            return "# Generated by DBDiff\n# On ".date('m/d/Y h:i:s a', time())."\n\n";
        }
        return "";
    }

    private function getContent() {
        $up = trim($this->up, "\n");
        return $up;
    }
}
